### ISSUE TITLE
`config` collection of a tenant doesn't get deleted

### ISSUE THREAD

**Issue by UncleSamSwiss** [kuzzleio/kuzzle-plugin-device-manager#134]
When deleting an existing device manager engine through 
```bash
kourou device-manager/engine:delete <index>
```
the collection `config` of the given index is not deleted.

Looking at the code, it doesn't seem to make sense to have a `config` collection at all - probably this is still a leftover of old code (`onUpdate()` also doesn't touch the collection).

Also, the index itself doesn't get deleted, but there might be a (good) reason for this.

**Comment by rolljee** [comment]
Hello @UncleSamSwiss 

The config collection is used by the plugin to store information about the device provisioning strategy and the internal configuration of the plugin.

It is normal that the config collection is not deleted because it is potentially used by other plugins that also store their configurations, deleting this collection will potentially make other plugins doesn't work properly

**Comment by UncleSamSwiss** [comment]
Thanks, this makes sense. I wasn't aware of the feature to "extend" mappings from other plugins.

This makes my life even easier :-)
